### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by iszhangsc** [Yuimng/vue3-admin-client#2]
我想使用你的的代码，想用 websocket 写了一个全局的通知， 通知组件用的是 ElNotification, 但是这个通知的位置始终不正确，他不在容器里面，感谢回复！！
我是在 main/index.vue 里面进行引入的我的websocket组件. 
这是我的组件代码
`<script setup lang="ts">
import { onMounted, onBeforeUnmount } from 'vue'
import { ElNotification } from 'element-plus'
import webSocketInstance from '@/main'

defineOptions({
  name: 'GlobalNotification'
})
onMounted(() => {
  webSocketInstance.initWebSocket()

  // 添加监听器
  webSocketInstance.addMessageListener('NOTIFICATION', (data) => {
    console.log('Received data:', data)
    ElNotification({
      customClass: 'global-notification',
      type: data.type,
      title: data.title,
      message: data.message,
      duration: 0,
      offset: 100
    })
  })
})

onBeforeUnmount(() => {
  webSocketInstance.closeWebSocket()
})
</script>

<style lang="scss"></style>
`
![image](https://github.com/user-attachments/assets/ce88d705-914e-4490-b889-cbf654b4f957)

![image](https://github.com/user-attachments/assets/90b00408-48fd-4949-a5ae-3454d664b440)

**Comment by Yuimng** [comment]
你可能是没有给 el-notification导入它的组件样式

**Comment by Yuimng** [comment]
你应该是没有给 el-notification 导入它的样式
在main.ts 导入试试
```typescript
// el-notification css
import 'element-plus/es/components/notification/style/css'
```

**Comment by iszhangsc** [comment]
还真是。 感谢🙏
